### ISSUE TITLE
フロント起動時に504エラーになる問題

### ISSUE THREAD

**Issue by ruiinoue** [ruiinoue/todo-app#18]
フロントを立ち上げたときに504エラーで立ち上がらなくなったのを解決したい

**Comment by ruiinoue** [comment]
`ERROR [HPM] Error occurred while trying to proxy request`

↑のエラーにしたがって`proxy`に問題がないのかを確認する。
http://pokuwagata.hatenablog.com/entry/2019/07/28/191649

そもそも最初のセットアップのときに確認していた内容で問題なかったから、フロント側で起きている問題ではなさそう。。。

**Comment by ruiinoue** [comment]
サーバー側がうまく起動していなかったことが判明！

```
backend     | => Booting Puma
backend     | => Rails 6.0.3.4 application starting in development 
backend     | => Run `rails server --help` for more startup options
backend     | A server is already running. Check /app/tmp/pids/server.pid.
backend     | Exiting
```

`app/tmp/pids/server.pid`ファイルがすでに存在してしまっていたからサーバーが起動できない感じだった。

**Comment by ruiinoue** [comment]
docker-compose up で`app/tmp/pids/server.pid`ファイルが削除されるような仕組みにしてしまえば今後も対策できるようになる。これでいったん解決。
https://qiita.com/paranishian/items/862ce4de104992df48e1

```
・・・
backend:
    container_name: backend
    build: ./backend/
    image: backend
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
・・・
```

サーバーの立ち上げ時に`tmp/pids/server.pid`ファイルを削除するコマンドを追加。

https://github.com/ruiinoue/todo-app/pull/16/commits/10066273d6780e7099a07036b4f2d36dd29a0137
